conversation_style:
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
dialogue_structure:
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"
podcast_name: "PODCASTIFY"
podcast_tagline: "Your Personal Generative AI Podcast"
output_language: "Korean"
engagement_techniques:
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1
user_instructions: ""
max_num_chunks: 4 # maximum number of rounds of discussions in longform (adjusted for ~10 min podcast)
min_chunk_size: 2000 # minimum number of characters to generate a round of discussion in longform (adjusted for ~10 min podcast)

text_to_speech:
  default_tts_model: "openai"
  output_directories:
    transcripts: "./data/transcripts"
    audio: "./data/audio"
  elevenlabs:
    default_voices:
      question: "Chris"
      answer: "Jessica"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "ko-KR-SunHiNeural"
      answer: "ko-KR-InJoonNeural"
  gemini:
    default_voices:
      question: "en-US-Journey-D"
      answer: "en-US-Journey-O"
  geminimulti:
    default_voices:
      question: "R"
      answer: "S"
      model: "en-US-Studio-MultiSpeaker"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "다음에 또 만나요!"
